// 技能列表

import { HeroSkill, HeroSkillAttackType, HeroSpecialAttackType, HeroSkillType } from "./skill";

const heroSkillMap: Map<string, HeroSkill> = new Map([
    ["1",
        {
            id: "1",
            name: "圣光术",
            imageName: "shengguangshu",
            type: HeroSkillType.active,
            description: "可以医疗友方活生生的部队或伤害敌方部队。一级时治疗300点生命点数，耗魔100；二级治疗400点，耗魔125；三级治疗500点，耗魔150；四级治疗600点，耗魔175。冷却时间为22秒‌。",
            doTimeSecond: 0,
            cdTimeSecond: 1,
            attackType: HeroSkillAttackType.singleAttack,
            specialAttack: HeroSpecialAttackType.null,
            basicAttack: 50,
        }
    ],
    ["5",
        {
            id: "5",
            name: "龙卷风暴‌",
            imageName: "longjuanfengbao",
            type: HeroSkillType.active,
            description: "召唤疾风力量赋予刀身，蓄力后向前方范围敌人释放一道龙卷风（或挥出强力的一刀），造成高额伤害。",
            doTimeSecond: 0,
            cdTimeSecond: 1,
            attackType: HeroSkillAttackType.singleAttack,
            specialAttack: HeroSpecialAttackType.null,
            basicAttack: 50,
        }
    ],
    ["9",
        {
            id: "9",
            name: "霸阳",
            imageName: "bayang",
            type: HeroSkillType.active,
            description: "在战斗中，张飞的伤害加成可以提升4%。",
            doTimeSecond: 0,
            cdTimeSecond: 1,
            attackType: HeroSkillAttackType.singleAttack,
            specialAttack: HeroSpecialAttackType.null,
            basicAttack: 50,
        }
    ],
    ["13",
        {
            id: "13",
            name: "治疗",
            imageName: "zhiliao",
            type: HeroSkillType.active,
            description: "全体生命值恢复10%，冷却时间10秒。",
            doTimeSecond: 0,
            cdTimeSecond: 1,
            attackType: HeroSkillAttackType.singleAttack,
            specialAttack: HeroSpecialAttackType.null,
            basicAttack: 50,
        }
    ],
    ["17",
        {
            id: "17",
            name: "陷阵",
            imageName: "xianzhen",
            type: HeroSkillType.active,
            description: "生命高于50%时释放该技能，损失自身5%生命值，造成敌方群体伤害。",
            doTimeSecond: 0,
            cdTimeSecond: 1,
            attackType: HeroSkillAttackType.singleAttack,
            specialAttack: HeroSpecialAttackType.null,
            basicAttack: 50,
        }
    ],
    ["21",
        {
            id: "21",
            name: "散华",
            imageName: "sanhua",
            type: HeroSkillType.active,
            description: "能够对群体敌军造成自身攻击力的300%伤害。",
            doTimeSecond: 0,
            cdTimeSecond: 1,
            attackType: HeroSkillAttackType.singleAttack,
            specialAttack: HeroSpecialAttackType.null,
            basicAttack: 50,
        }
    ],
    ["25",
        {
            id: "25",
            name: "‌枭雄",
            imageName: "xiaoxiong",
            type: HeroSkillType.active,
            description: "在战斗中提升一定百分比的防御力，增强友方的生存能力‌。",
            doTimeSecond: 0,
            cdTimeSecond: 1,
            attackType: HeroSkillAttackType.singleAttack,
            specialAttack: HeroSpecialAttackType.null,
            basicAttack: 50,
        }
    ],
    ["29",
        {
            id: "29",
            name: "‌强袭",
            imageName: "qiangxi",
            type: HeroSkillType.active,
            description: "战斗中触发暴击时，暴击伤害提升一定比例‌‌。",
            doTimeSecond: 0,
            cdTimeSecond: 1,
            attackType: HeroSkillAttackType.singleAttack,
            specialAttack: HeroSpecialAttackType.null,
            basicAttack: 50,
        }
    ],
    ["33",
        {
            id: "33",
            name: "鹰视狼顾",
            imageName: "yingshilanggu",
            type: HeroSkillType.active,
            description: "在战斗前四回合有80%的概率使得司马懿自身获得7%的攻心或奇谋几率，第五回合后有80%的概率对1-2个敌军单体造成谋略伤害，并且身为主将时还能获得额外的奇谋加成‌‌‌。",
            doTimeSecond: 0,
            cdTimeSecond: 1,
            attackType: HeroSkillAttackType.singleAttack,
            specialAttack: HeroSpecialAttackType.null,
            basicAttack: 50,
        }
    ],
    ["37",
        {
            id: "37",
            name: "鹰视狼顾",
            imageName: "yingshilanggu",
            type: HeroSkillType.active,
            description: "在战斗前四回合有80%的概率使得司马懿自身获得7%的攻心或奇谋几率，第五回合后有80%的概率对1-2个敌军单体造成谋略伤害，并且身为主将时还能获得额外的奇谋加成‌‌‌。",
            doTimeSecond: 0,
            cdTimeSecond: 1,
            attackType: HeroSkillAttackType.singleAttack,
            specialAttack: HeroSpecialAttackType.null,
            basicAttack: 50,
        }
    ],
    ["41",
        {
            id: "41",
            name: "绝情",
            imageName: "jueqing",
            type: HeroSkillType.active,
            description: "",
            doTimeSecond: 0,
            cdTimeSecond: 1,
            attackType: HeroSkillAttackType.singleAttack,
            specialAttack: HeroSpecialAttackType.null,
            basicAttack: 50,
        }
    ],
    ["45",
        {
            id: "45",
            name: "君威",
            imageName: "junwei",
            type: HeroSkillType.active,
            description: "‌提升孙权在战斗中的攻击力，最高可达8%。",
            doTimeSecond: 0,
            cdTimeSecond: 1,
            attackType: HeroSkillAttackType.singleAttack,
            specialAttack: HeroSpecialAttackType.null,
            basicAttack: 50,
        }
    ],
    ["49",
        {
            id: "49",
            name: "苦肉技",
            imageName: "kurouji",
            type: HeroSkillType.active,
            description: "",
            doTimeSecond: 0,
            cdTimeSecond: 1,
            attackType: HeroSkillAttackType.singleAttack,
            specialAttack: HeroSpecialAttackType.null,
            basicAttack: 50,
        }
    ],
    ["53",
        {
            id: "53",
            name: "攻骑",
            imageName: "gongqi",
            type: HeroSkillType.active,
            description: "",
            doTimeSecond: 0,
            cdTimeSecond: 1,
            attackType: HeroSkillAttackType.singleAttack,
            specialAttack: HeroSpecialAttackType.null,
            basicAttack: 50,
        }
    ],
    ["57",
        {
            id: "57",
            name: "待定",
            imageName: "gongqi",
            type: HeroSkillType.active,
            description: "",
            doTimeSecond: 0,
            cdTimeSecond: 1,
            attackType: HeroSkillAttackType.singleAttack,
            specialAttack: HeroSpecialAttackType.null,
            basicAttack: 50,
        }
    ],
]);

